# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: resourcehub

container: quay.io/lucarval/rhtap-task-runner:latest

variables:
- group: acmiel-variables

steps:
- script: cosign version
  displayName: Check if we have cosign

- script: |
    #!/bin/bash
    set -euo pipefail

    echo "${COSIGN_PUBLIC_KEY}"
    # don't worry, the value will get censored
    echo "${COSIGN_SECRET_KEY}"

    echo "And here are all the env var!"
    env
  displayName: Running a script
  env:
    # normal variables are set automatically, but secrets have to be set explicitly :(
    COSIGN_SECRET_KEY: $(COSIGN_SECRET_KEY)

- script: |
    #!/bin/bash
    set -euo pipefail
    
    timestamp() {                                                                                          
      date -u +"%Y-%m-%dT%H:%M:%SZ"                                                                      
    } 
    
    export BASE_RESULTS="$(mktemp -d)"
    mkdir "${BASE_RESULTS}/init"
    timestamp > "${BASE_RESULTS}/init/START_TIME"
    mkdir "${BASE_RESULTS}/buildah-rhtap"
    echo -n 'some-blob-url-test' > "${BASE_RESULTS}/buildah-rhtap/SBOM_BLOB_URL"
    
    bash /work/rhtap/att-predicate-azure.sh

  displayName: Generate provenance
  env:
    # normal variables are set automatically, but secrets have to be set explicitly :(
    COSIGN_SECRET_KEY: $(COSIGN_SECRET_KEY)
